name: CI
on: [push, pull_request]
env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  checks:
    name: Linting and Type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run lint
      - run: npm run test:types

  dom-tests:
    name: Unit and Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: mujo-code/puppeteer-headful@master
      - run: npm install
      - run: npm run test:dom

  functional-tests:
    name: Chromium Functional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: mujo-code/puppeteer-headful@master
      - run: npm install
      - run: npm run test:functional
        env:
          PUPPETEER_BROWSER: chromium

  publish:
    if: ${{ startsWith(github.event.commits[0].message, 'docs:') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run clean
          npm run build:ci
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
